version: '3.1'

services:
  app:
    image: hippam:latest
    volumes:
      - ${APP_SRC}:/home/bagus/app
      - ./volumes/workers:/etc/workers
    ports:
      - ${APP_PORT}:80
    networks:
      - hippam

  db:
    container_name: mysql
    image: mysql:8.0
    command: mysqld --sql_mode="traditional" --default-authentication-plugin=mysql_native_password --log_bin_trust_function_creators=1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - hippam

  # db:
  #   container_name: pgsql-pln
  #   image: postgres:12-alpine
  #   volumes:
  #     - ./volumes/db:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=root
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=pln-be
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - pln-be

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - hippam

networks:
  hippam:
    driver: bridge
